name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
        
        
      - name: Run test database
        run: |
          docker compose build
          docker compose run -d database

      - name: Run unit tests
        run: poetry run invoke test --unit
        env:
          TEST_DATABASE_URL: postgresql://postgres:ohtu@database:5432 
      
      # - name: Run tests
        # run: docker compose run test-runner poetry run coverage run --branch -m pytest && poetry run invoke coverage-report -t xml

      # - name: Run Robot tests
      #   run: docker compose run test-runner poetry run invoke robot-test -b headlesschrome

      #- name: Generate code coverage report
      #  run: docker compose run test-runner poetry run invoke coverage-report -t xml
        
      
      #- name: Generate code coverage report
      #  run: docker compose run test-runner poetry run invoke coverage-report -t html
        
        ###
      
      
        
      #- name: Run tests
      #  run: docker compose run test-runner poetry run coverage run --branch -m pytest 
        
      #- name: Coverage report
      #  run: docker compose run test-runner poetry run coverage xml
        
      # - name: Coverage report to Codecov
        # run: bash <(curl -s https://codecov.io/bash)

        
