name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TEST_DATABASE_PASSWORD=testing
  TEST_DATABASE_URL: postgresql://postgres:testing@localhost:5432 

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
        
        
      - name: Run test database
        run: docker run -p 5432:5432 -e POSTGRES_PASSWORD=$TEST_DATABASE_PASSWORD -d postgres:latest

      - name: Run unit tests
        run: poetry run invoke test --unit
